import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

esbuild.build({
	banner: { js: banner },
	entryPoints: ["main.ts"],
	bundle: true,
	external: ["obsidian", "electron", ...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	loader: {
		".json": "json",   // Inline JSON files
		".wasm": "dataurl" // Inline WASM files as data URLs
	}
}).catch(() => process.exit(1));
